// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_hash, name, is_active)
VALUES ($1, $2, true)
RETURNING id, key_hash, name, created_at, last_used_at, is_active
`

type CreateAPIKeyParams struct {
	KeyHash string
	Name    string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.KeyHash, arg.Name)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return &i, err
}

const updateLastUsed = `-- name: UpdateLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE key_hash = $1
`

func (q *Queries) UpdateLastUsed(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, updateLastUsed, keyHash)
	return err
}

const validateAPIKey = `-- name: ValidateAPIKey :one
SELECT EXISTS(
    SELECT 1 FROM api_keys
    WHERE key_hash = $1 AND is_active = true
)
`

func (q *Queries) ValidateAPIKey(ctx context.Context, keyHash string) (bool, error) {
	row := q.db.QueryRow(ctx, validateAPIKey, keyHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
