// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, role, created_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return &i, err
}

const selectUserByID = `-- name: SelectUserByID :one
SELECT id, username, password_hash, role, created_at FROM users WHERE id = $1
`

func (q *Queries) SelectUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, selectUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return &i, err
}

const selectUserByUsername = `-- name: SelectUserByUsername :one
SELECT id, username, password_hash, role, created_at FROM users WHERE username = $1
`

func (q *Queries) SelectUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, selectUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return &i, err
}
