// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package db

import (
	"context"
)

const countAllCharacters = `-- name: CountAllCharacters :one
SELECT COUNT(*) FROM characters
`

func (q *Queries) CountAllCharacters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCharacters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    name, body_type, species, class, level, xp, hp_max, hp_current
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, body_type, species, class, level, xp, hp_max, hp_current
`

type CreateCharacterParams struct {
	Name      string
	BodyType  string
	Species   string
	Class     string
	Level     int32
	Xp        int32
	HpMax     int32
	HpCurrent int32
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (*Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.Name,
		arg.BodyType,
		arg.Species,
		arg.Class,
		arg.Level,
		arg.Xp,
		arg.HpMax,
		arg.HpCurrent,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BodyType,
		&i.Species,
		&i.Class,
		&i.Level,
		&i.Xp,
		&i.HpMax,
		&i.HpCurrent,
	)
	return &i, err
}

const createCustomization = `-- name: CreateCustomization :one
INSERT INTO customizations (
    character_id, hair, face, shirt, pants, shoes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING character_id, hair, face, shirt, pants, shoes
`

type CreateCustomizationParams struct {
	CharacterID int64
	Hair        int16
	Face        int16
	Shirt       int16
	Pants       int16
	Shoes       int16
}

func (q *Queries) CreateCustomization(ctx context.Context, arg CreateCustomizationParams) (*Customization, error) {
	row := q.db.QueryRow(ctx, createCustomization,
		arg.CharacterID,
		arg.Hair,
		arg.Face,
		arg.Shirt,
		arg.Pants,
		arg.Shoes,
	)
	var i Customization
	err := row.Scan(
		&i.CharacterID,
		&i.Hair,
		&i.Face,
		&i.Shirt,
		&i.Pants,
		&i.Shoes,
	)
	return &i, err
}

const createStats = `-- name: CreateStats :one
INSERT INTO stats (
    character_id, strength, dexterity, constitution, intelligence, wisdom, charisma
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING character_id, strength, dexterity, constitution, intelligence, wisdom, charisma
`

type CreateStatsParams struct {
	CharacterID  int64
	Strength     int16
	Dexterity    int16
	Constitution int16
	Intelligence int16
	Wisdom       int16
	Charisma     int16
}

func (q *Queries) CreateStats(ctx context.Context, arg CreateStatsParams) (*Stat, error) {
	row := q.db.QueryRow(ctx, createStats,
		arg.CharacterID,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
	)
	var i Stat
	err := row.Scan(
		&i.CharacterID,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
	)
	return &i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters
WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCharacter, id)
	return err
}

const selectAllCharacters = `-- name: SelectAllCharacters :many
SELECT id, name, body_type, species, class, level, xp, hp_max, hp_current FROM characters
ORDER BY id
LIMIT $1 OFFSET $2
`

type SelectAllCharactersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) SelectAllCharacters(ctx context.Context, arg SelectAllCharactersParams) ([]*Character, error) {
	rows, err := q.db.Query(ctx, selectAllCharacters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BodyType,
			&i.Species,
			&i.Class,
			&i.Level,
			&i.Xp,
			&i.HpMax,
			&i.HpCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCharacter = `-- name: SelectCharacter :one
SELECT id, name, body_type, species, class, level, xp, hp_max, hp_current FROM characters
WHERE id = $1
`

func (q *Queries) SelectCharacter(ctx context.Context, id int64) (*Character, error) {
	row := q.db.QueryRow(ctx, selectCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BodyType,
		&i.Species,
		&i.Class,
		&i.Level,
		&i.Xp,
		&i.HpMax,
		&i.HpCurrent,
	)
	return &i, err
}

const selectCharacterCustomization = `-- name: SelectCharacterCustomization :one
SELECT character_id, hair, face, shirt, pants, shoes FROM customizations
WHERE character_id = $1
`

func (q *Queries) SelectCharacterCustomization(ctx context.Context, characterID int64) (*Customization, error) {
	row := q.db.QueryRow(ctx, selectCharacterCustomization, characterID)
	var i Customization
	err := row.Scan(
		&i.CharacterID,
		&i.Hair,
		&i.Face,
		&i.Shirt,
		&i.Pants,
		&i.Shoes,
	)
	return &i, err
}

const selectCharacterStats = `-- name: SelectCharacterStats :one
SELECT character_id, strength, dexterity, constitution, intelligence, wisdom, charisma FROM stats
WHERE character_id = $1
`

func (q *Queries) SelectCharacterStats(ctx context.Context, characterID int64) (*Stat, error) {
	row := q.db.QueryRow(ctx, selectCharacterStats, characterID)
	var i Stat
	err := row.Scan(
		&i.CharacterID,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
	)
	return &i, err
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters
SET name = $2, body_type = $3, species = $4, class = $5,
    level = $6, xp = $7, hp_max = $8, hp_current = $9
WHERE id = $1
RETURNING id, name, body_type, species, class, level, xp, hp_max, hp_current
`

type UpdateCharacterParams struct {
	ID        int64
	Name      string
	BodyType  string
	Species   string
	Class     string
	Level     int32
	Xp        int32
	HpMax     int32
	HpCurrent int32
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (*Character, error) {
	row := q.db.QueryRow(ctx, updateCharacter,
		arg.ID,
		arg.Name,
		arg.BodyType,
		arg.Species,
		arg.Class,
		arg.Level,
		arg.Xp,
		arg.HpMax,
		arg.HpCurrent,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BodyType,
		&i.Species,
		&i.Class,
		&i.Level,
		&i.Xp,
		&i.HpMax,
		&i.HpCurrent,
	)
	return &i, err
}

const updateCustomization = `-- name: UpdateCustomization :one
UPDATE customizations
SET hair = $2, face = $3, shirt = $4, pants = $5, shoes = $6
WHERE character_id = $1
RETURNING character_id, hair, face, shirt, pants, shoes
`

type UpdateCustomizationParams struct {
	CharacterID int64
	Hair        int16
	Face        int16
	Shirt       int16
	Pants       int16
	Shoes       int16
}

func (q *Queries) UpdateCustomization(ctx context.Context, arg UpdateCustomizationParams) (*Customization, error) {
	row := q.db.QueryRow(ctx, updateCustomization,
		arg.CharacterID,
		arg.Hair,
		arg.Face,
		arg.Shirt,
		arg.Pants,
		arg.Shoes,
	)
	var i Customization
	err := row.Scan(
		&i.CharacterID,
		&i.Hair,
		&i.Face,
		&i.Shirt,
		&i.Pants,
		&i.Shoes,
	)
	return &i, err
}

const updateStats = `-- name: UpdateStats :one
UPDATE stats
SET strength = $2, dexterity = $3, constitution = $4,
    intelligence = $5, wisdom = $6, charisma = $7
WHERE character_id = $1
RETURNING character_id, strength, dexterity, constitution, intelligence, wisdom, charisma
`

type UpdateStatsParams struct {
	CharacterID  int64
	Strength     int16
	Dexterity    int16
	Constitution int16
	Intelligence int16
	Wisdom       int16
	Charisma     int16
}

func (q *Queries) UpdateStats(ctx context.Context, arg UpdateStatsParams) (*Stat, error) {
	row := q.db.QueryRow(ctx, updateStats,
		arg.CharacterID,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
	)
	var i Stat
	err := row.Scan(
		&i.CharacterID,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
	)
	return &i, err
}
