// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForSeedItems implements pgx.CopyFromSource.
type iteratorForSeedItems struct {
	rows                 []SeedItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Type,
		r.rows[0].Description,
		r.rows[0].Equippable,
		r.rows[0].Rarity,
		r.rows[0].Damage,
		r.rows[0].Defense,
		r.rows[0].HealAmount,
		r.rows[0].ManaCost,
		r.rows[0].Duration,
		r.rows[0].Cooldown,
		r.rows[0].Capacity,
	}, nil
}

func (r iteratorForSeedItems) Err() error {
	return nil
}

func (q *Queries) SeedItems(ctx context.Context, arg []SeedItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"items"}, []string{"name", "type", "description", "equippable", "rarity", "damage", "defense", "heal_amount", "mana_cost", "duration", "cooldown", "capacity"}, &iteratorForSeedItems{rows: arg})
}
