// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addItemToCharacter = `-- name: AddItemToCharacter :one
INSERT INTO inventory (character_id, item_id, quantity, is_equipped)
VALUES ($1, $2, $3, false)
ON CONFLICT (character_id, item_id)
DO UPDATE SET quantity = inventory.quantity + EXCLUDED.quantity
RETURNING character_id, item_id, quantity, is_equipped
`

type AddItemToCharacterParams struct {
	CharacterID int64
	ItemID      int64
	Quantity    int32
}

func (q *Queries) AddItemToCharacter(ctx context.Context, arg AddItemToCharacterParams) (*Inventory, error) {
	row := q.db.QueryRow(ctx, addItemToCharacter, arg.CharacterID, arg.ItemID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.CharacterID,
		&i.ItemID,
		&i.Quantity,
		&i.IsEquipped,
	)
	return &i, err
}

const getCharacterInventory = `-- name: GetCharacterInventory :many
SELECT i.id             AS item_id,
       i.name,
       i.type,
       i.description,
       i.equippable,
       i.rarity,
       i.damage,
       i.defense,
       i.heal_amount,
       i.mana_cost,
       i.duration,
       i.cooldown,
       i.capacity,
       inv.quantity,
       inv.is_equipped
FROM inventory inv
JOIN items i ON i.id = inv.item_id
WHERE inv.character_id = $1
`

type GetCharacterInventoryRow struct {
	ItemID      int64
	Name        string
	Type        string
	Description string
	Equippable  bool
	Rarity      int32
	Damage      pgtype.Int4
	Defense     pgtype.Int4
	HealAmount  pgtype.Int4
	ManaCost    pgtype.Int4
	Duration    pgtype.Int4
	Cooldown    pgtype.Int4
	Capacity    pgtype.Int4
	Quantity    int32
	IsEquipped  bool
}

func (q *Queries) GetCharacterInventory(ctx context.Context, characterID int64) ([]*GetCharacterInventoryRow, error) {
	rows, err := q.db.Query(ctx, getCharacterInventory, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCharacterInventoryRow
	for rows.Next() {
		var i GetCharacterInventoryRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Equippable,
			&i.Rarity,
			&i.Damage,
			&i.Defense,
			&i.HealAmount,
			&i.ManaCost,
			&i.Duration,
			&i.Cooldown,
			&i.Capacity,
			&i.Quantity,
			&i.IsEquipped,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeItemFromCharacter = `-- name: RemoveItemFromCharacter :exec
WITH updated AS (
    UPDATE inventory
    SET quantity = inventory.quantity - $3
    WHERE inventory.character_id = $1 AND inventory.item_id = $2 AND inventory.quantity > $3
    RETURNING character_id
)
DELETE FROM inventory
WHERE inventory.character_id = $1 AND inventory.item_id = $2
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type RemoveItemFromCharacterParams struct {
	CharacterID int64
	ItemID      int64
	Quantity    int32
}

func (q *Queries) RemoveItemFromCharacter(ctx context.Context, arg RemoveItemFromCharacterParams) error {
	_, err := q.db.Exec(ctx, removeItemFromCharacter, arg.CharacterID, arg.ItemID, arg.Quantity)
	return err
}
