// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    name, type, description, equippable, rarity,
    damage, defense, heal_amount, mana_cost, duration,
    cooldown, capacity
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
RETURNING id, name, type, description, equippable, rarity, damage, defense, heal_amount, mana_cost, duration, cooldown, capacity
`

type CreateItemParams struct {
	Name        string
	Type        string
	Description string
	Equippable  bool
	Rarity      int32
	Damage      pgtype.Int4
	Defense     pgtype.Int4
	HealAmount  pgtype.Int4
	ManaCost    pgtype.Int4
	Duration    pgtype.Int4
	Cooldown    pgtype.Int4
	Capacity    pgtype.Int4
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (*Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Equippable,
		arg.Rarity,
		arg.Damage,
		arg.Defense,
		arg.HealAmount,
		arg.ManaCost,
		arg.Duration,
		arg.Cooldown,
		arg.Capacity,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Equippable,
		&i.Rarity,
		&i.Damage,
		&i.Defense,
		&i.HealAmount,
		&i.ManaCost,
		&i.Duration,
		&i.Cooldown,
		&i.Capacity,
	)
	return &i, err
}

const findAllItems = `-- name: FindAllItems :many
SELECT id, name, type, description, equippable, rarity, damage, defense, heal_amount, mana_cost, duration, cooldown, capacity FROM items
ORDER BY id
`

func (q *Queries) FindAllItems(ctx context.Context) ([]*Item, error) {
	rows, err := q.db.Query(ctx, findAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Equippable,
			&i.Rarity,
			&i.Damage,
			&i.Defense,
			&i.HealAmount,
			&i.ManaCost,
			&i.Duration,
			&i.Cooldown,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findItem = `-- name: FindItem :one
SELECT id, name, type, description, equippable, rarity, damage, defense, heal_amount, mana_cost, duration, cooldown, capacity FROM items
WHERE id = $1
`

func (q *Queries) FindItem(ctx context.Context, id int64) (*Item, error) {
	row := q.db.QueryRow(ctx, findItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Equippable,
		&i.Rarity,
		&i.Damage,
		&i.Defense,
		&i.HealAmount,
		&i.ManaCost,
		&i.Duration,
		&i.Cooldown,
		&i.Capacity,
	)
	return &i, err
}

type SeedItemsParams struct {
	Name        string
	Type        string
	Description string
	Equippable  bool
	Rarity      int32
	Damage      pgtype.Int4
	Defense     pgtype.Int4
	HealAmount  pgtype.Int4
	ManaCost    pgtype.Int4
	Duration    pgtype.Int4
	Cooldown    pgtype.Int4
	Capacity    pgtype.Int4
}
